# Generated by Django 5.0.1 on 2024-02-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AniBlogsWebsite", "0002_paidpromotion_alter_blog_blogcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paidpromotion",
            name="ReadBlogsBanner",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="ActualDate",
            field=models.CharField(default="27-02-2024", max_length=40),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="Date",
            field=models.CharField(default="2024-02-27 11:16:22.113149", max_length=40),
        ),
        migrations.AlterField(
            model_name="contactdetail",
            name="Date_added",
            field=models.CharField(default="2024-02-27 11:16:22.113149", max_length=40),
        ),
    ]
