# Generated by Django 5.0.1 on 2024-02-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AniBlogsWebsite", "0003_paidpromotion_readblogsbanner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="Date",
            field=models.CharField(default="2024-02-27 11:24:35.086490", max_length=40),
        ),
        migrations.AlterField(
            model_name="contactdetail",
            name="Date_added",
            field=models.CharField(default="2024-02-27 11:24:35.086490", max_length=40),
        ),
        migrations.DeleteModel(
            name="MoreUserDetail",
        ),
    ]
