# Generated by Django 5.0.1 on 2024-02-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AniBlogsWebsite", "0004_alter_blogcomment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="Date",
            field=models.CharField(default="2024-02-27 12:21:02.832755", max_length=40),
        ),
        migrations.AlterField(
            model_name="contactdetail",
            name="Date_added",
            field=models.CharField(default="2024-02-27 12:21:02.832755", max_length=40),
        ),
    ]
