# Generated by Django 5.0.1 on 2024-03-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AniBlogsWebsite", "0006_delete_contactdetail_alter_blogcomment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="BlogCategory",
            field=models.CharField(
                choices=[
                    ("Top Trends", "Top Trends"),
                    ("Entertainment", "Entertainment"),
                    ("Shark Tank India", "Shark Tank India"),
                    ("Technology", "Technology"),
                    ("Good Reads", "Good Reads"),
                    ("Python", "Python"),
                    ("Business News", "Business News"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="BlogImage",
            field=models.CharField(default="", max_length=5000),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="ActualDate",
            field=models.CharField(default="02-03-2024", max_length=40),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="Date",
            field=models.CharField(default="2024-03-02 10:59:27.299666", max_length=40),
        ),
    ]
