# Generated by Django 5.0.1 on 2024-03-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AniBlogsWebsite", "0008_alter_blogcomment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="Date",
            field=models.CharField(default="2024-03-02 11:10:32.988281", max_length=40),
        ),
    ]
