# Generated by Django 5.0.1 on 2024-04-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AniBlogsWebsite", "0009_alter_blogcomment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="BlogCategory",
            field=models.CharField(
                choices=[
                    ("Top Trends", "Top Trends"),
                    ("Failure Chronicles", "Failure Chronicles"),
                    ("Entertainment", "Entertainment"),
                    ("Shark Tank India", "Shark Tank India"),
                    ("Technology", "Technology"),
                    ("Good Reads", "Good Reads"),
                    ("Python", "Python"),
                    ("Business News", "Business News"),
                ],
                default="",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="ActualDate",
            field=models.CharField(default="20-04-2024", max_length=40),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="Date",
            field=models.CharField(default="2024-04-20 22:50:01.392704", max_length=40),
        ),
    ]
